import './accounts'
import './deploy-test-token'
import './deploy-test-wftm'
import './add-liquidity'
import './set-in-private-mode'
import './whitelistTokens'
import './set-prices-with-bits'
import './set-fees'
import './gen-account'
import './set-spread'
import './set-max-global-sizes'
import './contracts-address'
import './withdraw-fees'

import './stake'